services:
  - type: web
    name: pgrs-lafic-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NOTION_DATABASE_ID
        value: 3b0d14c78a5680ef907cf5977a6148dd
      - key: NOTION_TOKEN
        sync: false

staticSites:
  - type: static
    name: pgrs-lafic-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: pgrs-lafic-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
  - type: static
    name: pgrs-lafic-app
    rootDir: app
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: BACKEND_URL
        fromService:
          name: pgrs-lafic-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL