services:
  - type: web
    name: app-de-bancada-lafic
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NOTION_DATABASE_ID
        value: 3b0d14c78a5680ef907cf5977a6148dd
      - key: NOTION_TOKEN
        sync: false
      - key: CORS_ORIGIN
        value: https://caetanoronan.github.io
